#!/bin/bash

service nginx stop
deluser nginx; delgroup nginx
addgroup --system nginx; adduser --system --ingroup nginx nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx start

