#!/usr/bin/env bash
# install haproxy and load balancing

sudo apt-get update
sudo apt-get install haproxy -y

echo "
frontend rurangwacodes_frontend
    bind *:80
    mode http
    default_backend rurangwacodes_backend

backend rurangwacodes_backend
    balance roundrobin
    server web-01 54.89.147.123 check
    server web-02 107.22.129.234 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
