#!/bin/bash

# Install nginx
apt-get update
apt-get install -y nginx

# Ensure nginx is running
service nginx start

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
kill -s HUP $(cat /var/run/nginx.pid)

# Create a default HTML page containing the required string
echo "Holberton School for the win!" > /var/www/html/index.html

